-- Your SQL goes here

CREATE TABLE CLIENTS
(
    ID           INTEGER PRIMARY KEY AUTOINCREMENT,
    FIRST_NAME   TEXT    NOT NULL,
    LAST_NAME    TEXT    NOT NULL,
    MOBILE       INTEGER NOT NULL,
    PHOTO        TEXT    NOT NULL,
    TIME_CREATED TEXT    NOT NULL
);
